### ISSUE TITLE
spiralsearch bug

### ISSUE THREAD

**Issue by norecha** [any-other-guy/Endless-Chaos-LostArk#1]
I believe everywhere you are calling spiralSearch, `entry[0]` and `entry[1]` should be swapped.

Like below, you are passing width first to spiralSearch, so `entry[0]` would return x coordinate. And you wouldn't need to check boundaries because spiralsearch doesnt produce out of bound values.
what you have still works because getpixel is using the same order, but the order you are searching through is not really spiral
```
    order = spiralSearch(width, height, math.floor(width / 2), math.floor(height / 2))
    for entry in order:
        if entry[1] >= width or entry[0] >= height:
            continue
        r, g, b = minimap.getpixel((entry[1], entry[0]))
        if (r in range(75, 85) and g in range(140, 150) and b in range(250, 255)) or (
            r in range(120, 130) and g in range(210, 220) and b in range(250, 255)
        ):
            left, top, _w, _h = config["regions"]["minimap"]
            states["moveToX"] = left + entry[1]
            states["moveToY"] = top + entry[0]
```

**Comment by cielthephantom2** [comment]
@norecha i get trouble with directional , my char alway skill to empty area .. elite alway in my back

**Comment by any-other-guy** [comment]
Sorry for the late reply.

The minimap is a 2d array like ```minimap[row][col]```, with the top-left most point as the (0, 0) origin point. The ```entry[0]``` represents the row position, it means the height from the top-left origin point, ```entry[1]``` represent the column position, which is the width.

**Comment by any-other-guy** [comment]
> @norecha i get trouble with directional , my char alway skill to empty area .. elite alway in my back and its just move far from red mobs

Since the bot is implemented with image recognition. During combat, it frequently scans the minimap to get the position of elites/mobs. There could be a lot of mis-judgements due to the implementation, but overall it does the job well enough to clear chaos dungeon in a timely and stable manner in my opinion. But yea more work could be put into it to eliminate number of mis-judgements.

**Comment by norecha** [comment]
> Sorry for the late reply.
> 
> The minimap is a 2d array like `minimap[row][col]`, with the top-left most point as the (0, 0) origin point. The `entry[0]` represents the row position, it means the height from the top-left origin point, `entry[1]` represent the column position, which is the width.

`entry[0]` represents the X coordinate because you are passing `width` as first argument; and you are supposed to add it on top your `left` param. and it should also be `getpixel(entry[0], entry[1])`.

Let me give some real numbers to help:
Imagine you have a width=1000, height=10 minimap. You call
```
bot.spiralSearch(1000, 10, 500, 5)

which returns
[(500, 5), (500, 6), (501, 6), (501, 5)....

which means entry[0] = 500, entry[1] = 5; for the first result.
```

Now first coordinate you should check should be (x=500, y=5). but you are calling `minimap.getpixel((entry[1], entry[0]))`, which would be (5, 500) which is not even inside the boundary of minimap. That's why you are forced to check boundaries before that since you are passing them in wrong order. Does that make sense?
