### ISSUE TITLE
Disconnection detected...

### ISSUE THREAD

**Issue by Nifroz** [any-other-guy/Endless-Chaos-LostArk#10]
Hi. The repository works until the enter confirmation screen appears is detected as a disconnection, after that enters into a loop. Not sure if I'm missing something, this didn't happen before until today's update. Thank you.

**Comment by any-other-guy** [comment]
I have been working and testing on lopang daily and guild donation features for the past few days, some of the commits are buggy.
but it should be good now

**Comment by any-other-guy** [comment]
There are quite a few settings regarding the lopang daily procedure, including very specific bifrost location.

i would recommend you to roll back to the bot version prior to Nov 10 for the time being

Soon I will finish testing this part and put specific instruction in the readme file.
