### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zongxingye** [any-other-guy/Endless-Chaos-LostArk#11]
想问一下有人现在steam服用么？

**Comment by a912350568** [comment]
可以用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "any-other-guy/Endless-Chaos-LostArk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月14日(星期一) 中午12:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[any-other-guy/Endless-Chaos-LostArk] question (Issue #11)





 
想问一下有人现在steam服用么？

**Comment by any-other-guy** [comment]
steam服可以用。用前要根据config.py和abilitie.py里配置游戏和脚本的一些设置
