### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by schrottsimon** [any-other-guy/Endless-Chaos-LostArk#12]
After running python3 .\bot.py i get the Error: "NotImplementedError: The confidence keyword argument is only available if OpenCV is installed." Although OpenCV is installed 

> >>> import cv2
>>> cv2.__version__
'4.6.0'
>>>

>

**Comment by any-other-guy** [comment]
did you run ```pip install -r requirements.txt``` ?

**Comment by schrottsimon** [comment]
Yes.

**Comment by any-other-guy** [comment]
i read somewhere and it suggested there might be version conflict between opencv-python and numpy
try  ```pip install opencv-python==4.5.3.56```

**Comment by schrottsimon** [comment]
How do you setup the multiCharacterMode correctly? If I start on a random char it repairs, does guild donation, then lopang and then switches back to main character for endless chaos. ("just finished last char before main, closing multi-char mode")
