### ISSUE TITLE
Requesting Feature

### ISSUE THREAD

**Issue by gangagg** [any-other-guy/Endless-Chaos-LostArk#14]
Hi,

First of all, thank you for your code, it works really well so far.

I have a request for feature implementation for auto-repair.

Is it possible to implement auto repair without crystal aura and just stand beside the repair NPC and repair once Chaos Dungeon is finished?

Thanks!

**Comment by 85256638** [comment]
thanks for provding the excellent bot, I'm looking forward to the same feature

**Comment by 85256638** [comment]
I managed to add tweak the code, and enable the NPC repair function. Please ensure you stand near the repair NPC. I don't know how to make contribution using Git, but please find the bot.py file modified by myself.

The bot will use the NPC repair if the following conditions are met:

1. "City loaded" is true
2. NPC is nearby

[bot.txt](https://github.com/any-other-guy/Endless-Chaos-LostArk/files/10117225/bot.txt)

**Comment by any-other-guy** [comment]
Hi, I have updated the in-city repair option. Thanks for suggesting!
Happy farming!
