### ISSUE TITLE
Bot wont enter Dungeon

### ISSUE THREAD

**Issue by Nackenkelle** [any-other-guy/Endless-Chaos-LostArk#3]
i disabled shortcutEnterChaos but after starting the bot and opening the dungeon browser it wont click enter
Bot also locks south vern after starting with shortcutEnterChaos  enabled

**Comment by any-other-guy** [comment]
Hello, for disabled shortcutEnterChaos, you need to stand besides any of the chaos dungeon enter, with the interact icon showing on your screen.
Right now it does only lock with south vern 1445 for floor2 runs, I can make more lower ilvl options in the near future for my alts tho
