### ISSUE TITLE
"You are in a situation or zone where Integrated Dungeon is unavailable."

### ISSUE THREAD

**Issue by is3inchesgoo** [any-other-guy/Endless-Chaos-LostArk#5]
When I turn on the bot I just get this constant thing showing up and my guy isnt using skills at all seems like the alt button is pressed down and its trying to do "alt+q" and nothing else no other skills are getting pressed like w e r a s d f.

Any fixes?

![Untitled](https://user-images.githubusercontent.com/112668722/188031402-4029984d-c204-46f3-a0ce-30b6b925365e.png)

**Comment by any-other-guy** [comment]
please turn it on in the city, it will enter chaos dungeon for you.

**Comment by is3inchesgoo** [comment]
thanks a lot man!
i should have known that was my problem
