### ISSUE TITLE
Exiting chaos after clearing first floor too early?

### ISSUE THREAD

**Issue by endlesstonothing** [any-other-guy/Endless-Chaos-LostArk#6]
After the portal to the second floor spawns my character will auto attack towards it a couple times and the mouse will click on the 'leave dungeon' button and exit the chaos dungeon although sometimes my character will succeed going into the second floor but it will exit about 90% of the time. 
Any solutions to what I'm doing wrong or is this intended behavior?

![Untitled](https://user-images.githubusercontent.com/112680128/188063538-a58bb201-64e2-4ba9-a5a2-925796daae90.png)

**Comment by endlesstonothing** [comment]
I was playing attack with right-click off

Solution: go to settings -> hotkeys -> basic controls -> check Attack with right-click or just change the move in config to 'right'

**Comment by any-other-guy** [comment]
not sure if my last message went through or not, but yeah I use left click to move my character in-game, that makes me set it as the default way of moving in this script. You can change it to either moving with left/right click in [config.py](../config.py) in the script, so you can keep your in-game moving setting as is.

To furthur explaining the behavior you described in the first post. The reason why the script is exiting chaos dungeon after your floor 1 clear is that, there is a timeout threshold for finding the portal to the next floor. In some cases, the path that the script set for your character to move into the portal is deviated from the correct path. Therefore, I put in the code that if you cannot get in the portal within 5s, just quit and start the next run. 

Such inconvenience is related to various issue/limitations with how I implemented the procedure. It does impact the overall income of materials ever so slightly, but it does not happen very frequently. I will consider a fix later on.
